### ISSUE TITLE
Memory Leak in SBPL2DGridSearch

### ISSUE THREAD

**Issue by vvanirudh** [sbpl/sbpl#36]
In line 397 of 2Dgridsearch.cpp, pbClosed is allocated using `calloc`:
`char *pbClosed = (char*)calloc(1, width_ * height_);`

But in line 465 of 2Dgridsearch.cpp, pbClosed is deallocated using `delete []`:
`delete[] pbClosed;`

Change the line to:
`free(pbClosed);`

This should take care of the memory leak. I could do a pull request but since it's such a small change, I thought I would just create an issue that the moderators can correct.

**Comment by aurone** [comment]
Thanks! The memory leak has been fixed.
