### ISSUE TITLE
Trouble while executing test_sbpl

### ISSUE THREAD

**Issue by chatrasen** [sbpl/sbpl#37]
After building the code, I ran the command ` ./test_sbpl -h ../env_examples/nav2d/env1.cfg
`
However, it threw an SBPL_Exception. Can anyone please tell the reason for this?

**Comment by aurone** [comment]
The example environments the nav2d directory require that you use a two-dimensional search space. In the test program, this is accomplished by using the `--env=2d` command-line option to override the default search space (x, y, theta). The final invocation should be `./test_sbpl --env=2d ../env_examples/nav2d/env1.cfg`
