### ISSUE TITLE
sol.txt is empty

### ISSUE THREAD

**Issue by kunal-iitkgp** [sbpl/sbpl#38]
@aurone can you tell me where am i going wrong?

after executing `./test_sbpl --env=2d ../env_examples/nav2d/env1.cfg`
I get the following results : 
`Environment: 2d; Planner: arastar; Search direction: backward
Initializing ARAPlanner...
start planning...
done planning
size of solution=22
Solution is found`

but the sol.txt file is empty

**Comment by aurone** [comment]
You'll need to edit sbpl/src/include/sbpl/config.h to change the `#define DEBUG 0` line to `#define DEBUG 1` and recompile to enable most of the prints and debug information.

**Comment by kunal-iitkgp** [comment]
hey thanks it worked .. but how does setting DEBUG to 1 prints the shortest path?

**Comment by aurone** [comment]
Environment2D::PrintState(...) uses SBPL_FPRINTF underneath to output the path to file, which is disabled when DEBUG is 0. You can check the rest of config.h for details; all sbpl print macros are handled this way.

**Comment by kunal-iitkgp** [comment]
@aurone thanks for the help
