### ISSUE TITLE
Example configurations are invalid format

### ISSUE THREAD

**Issue by PeterMitrano** [sbpl/sbpl#41]
I'm unable to run the test_sbpl program. Here's the command I tried:

```
./test_sbpl ../env_examples/nav2d/enc1.cfg
```

All the other arguments are optional it seems, so I'd expect this to work.

**Comment by aurone** [comment]
The default planning environment for the test program is the (x, y, theta) lattice environment, which will only work with the environment config files in sbpl/env_examples/nav3d. You can test out the 2d (x, y) environment by passing the --env=2d option to the test program along with one of environments in sbpl/env_examples/env1.cfg .

**Comment by PeterMitrano** [comment]
Thanks--I had figured this out when I ran the 3d example, and by checking out the actual error. It would be worth adding a note in the ReadMe about this, maybe listing a few examples that will work. Shall I PR that or would you prefer to do it yourself?

**Comment by aurone** [comment]
PR would be great.
