### ISSUE TITLE
New ROS release

### ISSUE THREAD

**Issue by mintar** [sbpl/sbpl#53]
Could you please make a new ROS release of SBPL? The previously released version (1.2.0) is very outdated by now. The master branch builds fine, so all that's needed would be a new [bloom release](http://wiki.ros.org/bloom/Tutorials/ReleaseCatkinPackage).

This might also be of interest to @robotpilot, but I don't know if he has write access to this repo. And without write access it's difficult or impossible to do the bloom release.

Once the new release has been done for Indigo and Kinetic, it would be great if the package could also be released into Lunar and Melodic. It builds fine on both distros, there are just some C++11 warnings on Melodic, but they can be safely ignored.

**Comment by robotpilot** [comment]
Hi @mintar,
Recently I am also preparing a melodic release for other packages that I manage. I will also release this SBPL with them.

**Comment by robotpilot** [comment]
For Lunar, https://github.com/ros/rosdistro/pull/18528
For Melodic, https://github.com/ros/rosdistro/pull/18529

**Comment by mintar** [comment]
Thanks @robotpilot , sbpl is now released for lunar and melodic.

*However*, what I'm really saying is that we need to tag a new version and release that. The released version is 1.2.0, which is 4 years old now. The `master` branch is 64 commits ahead of 1.2.0.

**Comment by robotpilot** [comment]
@mintar 
Unfortunately, I have only the permissions of the release repository and I don't have permission to create tags for the source code. https://github.com/ros-gbp/sbpl-release/issues/2

@aurone 
Can you create a new tag of the latest version to release?

**Comment by aurone** [comment]
@robotpilot Tagged the latest master as 1.3.1. Thanks for handling the ROS releases!

**Comment by robotpilot** [comment]
Hi @aurone
Thank you so much. I will prepare for release with the new tagged version. :)

**Comment by mintar** [comment]
Perfect, thanks @aurone @robotpilot !

**Comment by mintar** [comment]
The package is available from debs today. Many thanks again!
